-- Get tables from tablespace --
SELECT a.NAME AS space_name, b.NAME AS TABLE_NAME FROM INFORMATION_SCHEMA.INNODB_TABLESPACES a, INFORMATION_SCHEMA.INNODB_TABLES b WHERE a.SPACE=b.SPACE AND a.NAME LIKE 'tablespace';

